<?php

/*
 * Created by solutionDrive GmbH
 *
 * @copyright 2018 solutionDrive GmbH
 */

namespace sdShopEnvironment\Serializer\Normalizer;

use Shopware\Models\Country\Country;
use Shopware\Models\Dispatch\Dispatch;
use Shopware\Models\Dispatch\ShippingCost;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

class DispatchNormalizer extends ObjectNormalizer
{
    public function setAttributeValue($object, $attribute, $value, $format = null, array $context = [])
    {
        switch ($attribute) {
            case 'countries':
                if ($this->serializer instanceof DenormalizerInterface) {
                    $value = $this->serializer->denormalize($value, Country::class . '[]', $format);
                }
                break;

            case 'costsMatrix':
                if ($this->serializer instanceof DenormalizerInterface) {
                    $value = $this->serializer->denormalize($value, ShippingCost::class . '[]', $format);
                }
                break;
        }

        parent::setAttributeValue($object, $attribute, $value, $format, $context); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function supportsDenormalization($data, $type, $format = null)
    {
        return Dispatch::class === $type;
    }
}
